# /*
#  * Copyright (c) 2023 Software AG, Darmstadt, Germany and/or its licensors
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */

apiVersion: apps/v1
kind: {{ if .Values.statefulSet }}StatefulSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.extraLabels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if .Values.statefulSet }}
  serviceName: {{ .Values.serviceName | default (printf "msr-%s" (.Release.Name) ) }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "common.prometheus.annotations" (dict "port" .Values.service.port) | nindent 8 }}
        {{- if .Values.checksum }}
        checksum/config: {{ printf "%s%s%s%s" (include (print $.Template.BasePath "/configmap.yaml") .) (include (print $.Template.BasePath "/configmaps-extra.yaml") .) (include (print $.Template.BasePath "/secret.yaml") .) (include (print $.Template.BasePath "/license.yaml") .) | sha256sum }}
        {{- end }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
        {{- with .Values.extraLabels -}}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.names.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.extraInitContainers | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Values.containerName | default (printf "msr-%s" (.Release.Name) )}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.extraCommand }}
          command: ["/bin/sh", "-c", "{{ .Values.extraCommand }} && /opt/softwareag/IntegrationServer/bin/startContainer.sh"]
          {{- end }}
          env:
          - name: JAVA_MIN_MEM
            value: {{ .Values.microservicesruntime.memoryHeap.min }}
          - name: JAVA_MAX_MEM
            value: {{ .Values.microservicesruntime.memoryHeap.max }}
          - name: SAG_IS_LICENSE_FILE
            value: {{ .Values.microservicesruntime.installDir }}/licenseKey.xml
          - name: SAG_IS_CONFIG_PROPERTIES
            value: "{{ .Values.microservicesruntime.baseConfigDir }},{{ .Values.microservicesruntime.installDir }}/applicationFile.properties,{{ .Values.microservicesruntime.installDir }}/application.properties,{{ .Values.microservicesruntime.configDir}}"
          {{- if .Values.persistence.enabled }}
          - name: HOST_DIR
            value: {{ .Values.microservicesruntime.installDir }}/pv
          - name: SERVICE_NAME
            value: {{ .Release.Name }}
          - name: EXTERNALIZE_PACKAGES
            value: "{{ .Values.persistence.packages }}"
          - name: PERSIST_CONFIGS
            value: "{{ .Values.persistence.configs }}"
          - name: PERSIST_LOGS
            value: "{{ .Values.persistence.logs }}"
          {{- end }}
          {{- if .Values.microservicesruntime.javaCustomOpts }}
          {{- $element := .Values.microservicesruntime.javaCustomOpts }}
          {{- if eq (kindOf $element) "slice" }}
          - name: JAVA_CUSTOM_OPTS
            value: "{{ join " " .Values.microservicesruntime.javaCustomOpts }}"
          {{ else }}
          {{- $javaCustomOpts := list }}
          {{- range $key, $value := $element }}
          {{- $prop := (printf "-%s%s" $key $value) }}
          {{- $javaCustomOpts = append $javaCustomOpts $prop }}
          {{- end }}
          - name: JAVA_CUSTOM_OPTS
            value: "{{ join " " $javaCustomOpts }}"
          {{- end }}
          {{ end }}
          {{- if .Values.extraEnvs }}
          {{- toYaml .Values.extraEnvs | nindent 10 }}
          {{- end }}
          {{- include "common.metering.envs" . | nindent 10 }}
          ports:
          - containerPort: 5543
            name: https
            protocol: TCP
          - containerPort: 9999
            name: diag
            protocol: TCP
          - containerPort: 5555
            name: http
            protocol: TCP
          {{- if .Values.extraPorts }}
          {{- toYaml .Values.extraPorts | nindent 10 }}
          {{- end }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}           
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.msrContainer | nindent 12 }}
          volumeMounts:
            - name: microservicesruntime-license
              mountPath: {{ .Values.microservicesruntime.installDir }}/licenseKey.xml
              subPath:   licenseKey.xml
              readOnly:  true
            {{- if hasKey .Values.terracotta "license" }} 
            - name: terracotta-license
              mountPath: {{ .Values.microservicesruntime.installDir }}/../common/conf/terracotta-license.key
              subPath:   terracotta-license.key
              readOnly:  true
            {{- end }}
            - name: application-properties
              mountPath: {{ .Values.microservicesruntime.installDir }}/application.properties
              subPath:   application.properties
              readOnly:  true
            - name: applicationfile-properties
              mountPath: {{ .Values.microservicesruntime.installDir }}/applicationFile.properties
              subPath:   applicationFile.properties
              readOnly:  true
            {{- if .Values.persistence.enabled }}
            - name: persistence-assets
              mountPath: {{ .Values.microservicesruntime.installDir }}/pv
              readOnly:  false
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- if eq "string" (printf "%T" .Values.extraVolumeMounts) }}
              {{- tpl .Values.extraVolumeMounts . | nindent 12 }}
            {{- else if eq (kindOf .Values.extraVolumeMounts) "slice" }}
              {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- else }}
            {{- range $key, $vol := .Values.extraVolumeMounts }}
              {{- toYaml $vol | nindent 12 }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.extraConfigMaps }}
            {{- range $name, $map := .Values.extraConfigMaps }}
            {{- if $map.automount }}            
            {{- if $map.binaryData }}              
            {{- range $key, $val := $map.binaryData }}
            - name: {{ $name }}
              mountPath: {{ default $.Values.extraConfigMapAutomountDir $map.automountDir }}/{{ $key }}
              subPath: {{ $key }}
            {{- end }}
            {{- else }}
            {{- range $key, $val := $map.data }}
            - name: {{ $name }}
              mountPath: {{ $map.automountDir }}/{{ $key }}
              subPath: {{ $key }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}    
            {{- if .Values.secrets }}
            {{- range $name, $map := .Values.secrets }}
            {{- if $map.automount }} 
            - name: {{ $name }}
              mountPath: {{ default $.Values.secretAutomountDir $map.automountDir }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- range .Values.secretMounts }}
            - name: {{ .name }}
              mountPath: {{ .path }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
          {{- if .Values.lifecycle }}
          lifecycle:
{{ toYaml .Values.lifecycle | indent 12 }}
          {{- end }}
        {{- include "common.containers.extraContainers" . | nindent 8 }}
      volumes:
        {{- range .Values.secretVolumes }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
            {{- if .defaultMode }}
            defaultMode: {{ .defaultMode }}
            {{- end }}
        {{- end }}
        - name: microservicesruntime-license
          configMap:
            name: {{ include "microservicesruntime.licenseConfigMapName" . }}
            defaultMode: 0666
            items:
            - key:  licensekey
              path: licenseKey.xml
        {{- if .Values.terracotta.license }}
        - name: terracotta-license
          configMap:
            name: {{ include "microservicesruntime.licenseConfigMapName" . }}
            defaultMode: 0666
            items:
            - key:  terracotta-license.key
              path: terracotta-license.key
        {{- end }}
        - name: application-properties
          configMap:
            name: {{ include "common.names.fullname" . }}
            items:
            - key:  application.properties
              path: application.properties
        - name: applicationfile-properties
          configMap:
            name: {{ include "common.names.fullname" . }}
            items:
            - key:  applicationFile.properties
              path: applicationFile.properties
        {{- if .Values.persistence.enabled }}
        - name: persistence-assets
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "common.names.fullname" .) }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- if eq "string" (printf "%T" .Values.extraVolumes) }}
          {{ tpl .Values.extraVolumes . | nindent 8 }}
        {{- else if eq (kindOf .Values.extraVolumes) "slice" }}
          {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- else }}
          {{- range $key, $vol := .Values.extraVolumes }}
            {{- toYaml $vol | nindent 8 }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.extraConfigMaps }}
        # automount configmap volumes
        {{- range $name, $map := .Values.extraConfigMaps }}
        {{- if $map.automount }}                    
        - name: {{ $name }}
          configMap:
            name: {{ $name }}
            {{- if $map.defaultMode }}
            defaultMode: {{ $map.defaultMode }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}        
        {{- if .Values.secrets }}
        # automount secrets volumes
        {{- range $name, $map := .Values.secrets }}
        {{- if $map.automount }}                    
        - name: {{ $name }}
          secret:
            secretName: {{ $name }}
        {{- end }}
        {{- end }}
        {{- end }} 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if and .Values.statefulSet .Values.volumeClaimTemplates }}
  volumeClaimTemplates:
  {{- toYaml .Values.volumeClaimTemplates | nindent 2 }}
  {{- end }}