{{- range .Values.secrets }}
---
{{- if eq .kind "Secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- else if eq .kind "SealedSecret" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
spec:
  encryptedData:
{{- range $key, $value := .data }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
