{{- range $name, $map := .Values.secrets }}
---
{{- if eq .kind "Secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $map.name }}
type: {{ $map.type }}
data:
{{- range $key, $value := $map.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- else if eq .kind "SealedSecret" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $map.name }}
spec:
  encryptedData:
{{- range $key, $value := $map.data }}
    {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
